from .cards_def import get_card

DECKLIST = [
    ("Aerith Gainsborough", 1),
    ("Aetherflux Reservoir", 1),
    ("Ajani's Welcome", 1),
    ("Amalia Benavides Aguirre", 1),
    ("Anguished Unmaking", 1),
    ("Archangel of Thune", 1),
    ("Archivist of Oghma", 1),
    ("Ascend from Avernus", 1),
    ("Authority of the Consuls", 1),
    ("Barren Moor", 1),
    ("Blind Obedience", 1),
    ("Blood Artist", 1),
    ("Bolas's Citadel", 1),
    ("Brightclimb Pathway", 1),
    ("Case of the Uneaten Feast", 1),
    ("Caves of Koilos", 1),
    ("Charismatic Conqueror", 1),
    ("Cleric Class", 1),
    ("Command Tower", 1),
    ("Cruel Celebrant", 1),
    ("Damn", 1),
    ("Dark Confidant", 1),
    ("Daxos, Blessed by the Sun", 1),
    ("Deadly Rollick", 1),
    ("Deathgreeter", 1),
    ("Delney, Streetwise Lookout", 1),
    ("Elas il-Kor, Sadistic Pilgrim", 1),
    ("Elenda's Hierophant", 1),
    ("Esper Sentinel", 1),
    ("Essence Channeler", 1),
    ("Exotic Orchard", 1),
    ("Fetid Heath", 1),
    ("Flare of Fortitude", 1),
    ("Flawless Maneuver", 1),
    ("Godless Shrine", 1),
    ("Guide of Souls", 1),
    ("Heliod, Sun-Crowned", 1),
    ("Hinterland Sanctifier", 1),
    ("Isolated Chapel", 1),
    ("Kambal, Consul of Allocation", 1),
    ("Karlov of the Ghost Council", 1),
    ("Leonin Elder", 1),
    ("Lightning Greaves", 1),
    ("Lotho, Corrupt Shirriff", 1),
    ("Lunarch Veteran", 1),
    ("Lurrus of the Dream-Den", 1),
    ("Marauding Blight-Priest", 1),
    ("Marsh Flats", 1),
    ("Mother of Runes", 1),
    ("Mox Amber", 1),
    ("Ocelot Pride", 1),
    ("Orzhov Signet", 1),
    ("Path to Exile", 1),
    ("Plains", 7),
    ("Radiant Fountain", 1),
    ("Raise the Past", 1),
    ("Rally the Ancestors", 1),
    ("Rogue's Passage", 1),
    ("Sanguine Bond", 1),
    ("Secluded Steppe", 1),
    ("Selfless Spirit", 1),
    ("Sensei's Divining Top", 1),
    ("Serra Ascendant", 1),
    ("Shadowspear", 1),
    ("Shattered Sanctum", 1),
    ("Shineshadow Snarl", 1),
    ("Shizo, Death's Storehouse", 1),
    ("Silent Clearing", 1),
    ("Skullclamp", 1),
    ("Smothering Tithe", 1),
    ("Sol Ring", 1),
    ("Sorin of House Markov", 1),
    ("Soul Warden", 1),
    ("Soul's Attendant", 1),
    ("Spectrum Sentinel", 1),
    ("Starscape Cleric", 1),
    ("Suture Priest", 1),
    ("Swamp", 5),
    ("Swords to Plowshares", 1),
    ("Tainted Field", 1),
    ("Teferi's Protection", 1),
    ("The Meathook Massacre", 1),
    ("Toxic Deluge", 1),
    ("Urborg, Tomb of Yawgmoth", 1),
    ("Vault of Champions", 1),
    ("Vault of the Archangel", 1),
    ("Vito, Thorn of the Dusk Rose", 1),
    ("Voice of the Blessed", 1),
    ("Zulaport Cutthroat", 1),
]

def build_deck():
    deck = []
    for name, qty in DECKLIST:
        for _ in range(qty):
            deck.append(get_card(name))
    return deck 